import sys
import os
os.chdir('/Users/selina/Desktop/a/1/IBI/IBI1_2021-22/Practical8/')
print('Please input the file name here:')
filename=sys.stdin.readline()
newfile=open(filename+'.fa','w')
sequence=open('Saccharomyces_cerevisiae.R64-1-1.cdna.all.fa')
for line in sequence:
    number=0
    number=line.find('GAATTC')
    if number>=0:
        newfile.write('gene_name'+str(number+1)+' fragements could be generated by cutting thsi sequence with EcoRI\n')
newfile.close()